const PayoutActionTypes = {
    SET_SELECTED_ROWS: "SET_SELECTED_ROWS",

    PAY_USERS_START:"PAY_USERS_START",
    PAY_USERS_SUCCESS:"PAY_USERS_SUCCESS",
    PAY_USERS_FAILURE:"PAY_USERS_FAILURE",

    FETCH_PAY_HISTORY_START: "FETCH_PAY_HISTORY_START",
    FETCH_PAY_HISTORY_SUCCESS: "FETCH_PAY_HISTORY_SUCCESS",
    FETCH_PAY_HISTORY_FAILURE: "FETCH_PAY_HISTORY_FAILURE"
}

export default PayoutActionTypes