export const UserActionTypes = {
    SET_CURRENT_USER:"SET_CURRENT_USER",

    FETCH_USERS_START:"FETCH_USERS_START",
    FETCH_USERS_SUCCESS:"FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE:"FETCH_USERS_FAILURE"
}