export const PoActionTypes = {
    SET_ADD_MODE:"SET_ADD_MODE",
    SET_EDIT_MODE:"SET_EDIT_MODE",
    SET_VIEW_MODE:"SET_VIEW_MODE",

    FIND_PO_START: "FIND_PO_START",
    FIND_PO_SUCCESS: "FIND_PO_SUCCESS",
    FIND_PO_FAILURE: "FIND_PO_FAILURE",

    FETCH_PO_START: "FETCH_PO_START",
    FETCH_PO_SUCCESS:"FETCH_PO_SUCCESS",
    FETCH_PO_FAILURE:"FETCH_PO_FAILURE",

    SAVE_PO_START: "SAVE_PO_START",
    SAVE_PO_SUCCESS:"SAVE_PO_SUCCESS",
    SAVE_PO_FAILURE:"SAVE_PO_FAILURE",

    DOWNLOAD_PO_START: "DOWNLOAD_PO_START",
    DOWNLOAD_PO_FINISH:"DOWNLOAD_PO_FINISH",

    DELETE_PO_START: "DELETE_PO_START",
    DELETE_PO_FINISH:"DELETE_PO_FINISH",
}