export const PoActionTypes = {
    SET_PO_RESULT:"SET_PO_RESULT",
    SET_SEARCH_TEXT:"SET_SEARCH_TEXT",
    TOGGLE_VIEW_MODE:"TOGGLE_VIEW_MODE",
    TOGGLE_ADD_MODE:"TOGGLE_ADD_MODE",
    TOGGLE_EDIT_MODE:"TOGGLE_EDIT_MODE",
    SET_RECENT_PO:"SET_RECENT_PO",
    FETCH_RECENT_PO:"FETCH_RECENT_PO"
}