export const RecentPoActionTypes = {
    FETCH_RECENT_PO_START:"FETCH_RECENT_PO_START",
    FETCH_RECENT_PO_SUCCESS:"FETCH_RECENT_PO_SUCCESS",
    FETCH_RECENT_PO_FAILURE:"FETCH_RECENT_PO_FAILURE",
    SET_RECENT_PO_ALL:"SET_RECENT_PO_ALL"
}